# Generated by Django 4.0.5 on 2022-06-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chatmessage_msg_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='profile',
            new_name='profileme',
        ),
    ]
