# Generated by Django 4.0.5 on 2022-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_profile_friend_profileme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileme',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='core.friend'),
        ),
    ]
